In [1]:
import numpy as np

In [3]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
active_mask = [5,4,8,7,6,2]
a_adj = a[active_mask]
a_adj

array([5, 4, 8, 7, 6, 2])

In [13]:
indices = a_adj%4
indices

array([1, 0, 0, 3, 2, 2])

In [18]:
niveles_reales = np.array([10,20,30,40])
niveles_reales

array([10, 20, 30, 40])

In [19]:
potencias = niveles_reales[indices]
potencias

array([20, 10, 10, 40, 30, 30])

In [23]:
num_channels=3
P0=10
n_APs=2
high=np.array([[num_channels, P0]] * n_APs)
high

array([[ 3, 10],
       [ 3, 10]])